env:
  browser: true
  es6: true
  mocha: true
  node: true
parser: 'babel-eslint'
extends:
  - 'eslint:recommended'
  - 'prettier'
  - 'react-app'
parserOptions:
  ecmaVersion: 12
  sourceType: 'module'
  ecmaFeatures:
    classes: true
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-unused-vars:
    - warn
settings:
  react:
    pragma: React
    version: 16.8.0
